/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ProductIdRouteImport } from './routes/product/$id'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as DashboardProductsIndexRouteImport } from './routes/dashboard/products/index'
import { Route as DashboardPostsIndexRouteImport } from './routes/dashboard/posts/index'
import { Route as DashboardPostsNewRouteImport } from './routes/dashboard/posts/new'
import { Route as DashboardPostsIdRouteRouteImport } from './routes/dashboard/posts/$id/route'
import { Route as DashboardPostsIdIndexRouteImport } from './routes/dashboard/posts/$id/index'
import { Route as DashboardPostsIdEditRouteImport } from './routes/dashboard/posts/$id/edit'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardProductsIndexRoute = DashboardProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPostsIndexRoute = DashboardPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPostsNewRoute = DashboardPostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPostsIdRouteRoute = DashboardPostsIdRouteRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPostsIdIndexRoute = DashboardPostsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardPostsIdRouteRoute,
} as any)
const DashboardPostsIdEditRoute = DashboardPostsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => DashboardPostsIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/product/$id': typeof ProductIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/posts/$id': typeof DashboardPostsIdRouteRouteWithChildren
  '/dashboard/posts/new': typeof DashboardPostsNewRoute
  '/dashboard/posts/': typeof DashboardPostsIndexRoute
  '/dashboard/products/': typeof DashboardProductsIndexRoute
  '/dashboard/posts/$id/edit': typeof DashboardPostsIdEditRoute
  '/dashboard/posts/$id/': typeof DashboardPostsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/product/$id': typeof ProductIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/posts/new': typeof DashboardPostsNewRoute
  '/dashboard/posts': typeof DashboardPostsIndexRoute
  '/dashboard/products': typeof DashboardProductsIndexRoute
  '/dashboard/posts/$id/edit': typeof DashboardPostsIdEditRoute
  '/dashboard/posts/$id': typeof DashboardPostsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/product/$id': typeof ProductIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/posts/$id': typeof DashboardPostsIdRouteRouteWithChildren
  '/dashboard/posts/new': typeof DashboardPostsNewRoute
  '/dashboard/posts/': typeof DashboardPostsIndexRoute
  '/dashboard/products/': typeof DashboardProductsIndexRoute
  '/dashboard/posts/$id/edit': typeof DashboardPostsIdEditRoute
  '/dashboard/posts/$id/': typeof DashboardPostsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/about'
    | '/login'
    | '/register'
    | '/product/$id'
    | '/dashboard/'
    | '/dashboard/posts/$id'
    | '/dashboard/posts/new'
    | '/dashboard/posts/'
    | '/dashboard/products/'
    | '/dashboard/posts/$id/edit'
    | '/dashboard/posts/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/product/$id'
    | '/dashboard'
    | '/dashboard/posts/new'
    | '/dashboard/posts'
    | '/dashboard/products'
    | '/dashboard/posts/$id/edit'
    | '/dashboard/posts/$id'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/dashboard'
    | '/about'
    | '/_auth/login'
    | '/_auth/register'
    | '/product/$id'
    | '/dashboard/'
    | '/dashboard/posts/$id'
    | '/dashboard/posts/new'
    | '/dashboard/posts/'
    | '/dashboard/products/'
    | '/dashboard/posts/$id/edit'
    | '/dashboard/posts/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/dashboard/products/': {
      id: '/dashboard/products/'
      path: '/products'
      fullPath: '/dashboard/products/'
      preLoaderRoute: typeof DashboardProductsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/posts/': {
      id: '/dashboard/posts/'
      path: '/posts'
      fullPath: '/dashboard/posts/'
      preLoaderRoute: typeof DashboardPostsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/posts/new': {
      id: '/dashboard/posts/new'
      path: '/posts/new'
      fullPath: '/dashboard/posts/new'
      preLoaderRoute: typeof DashboardPostsNewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/posts/$id': {
      id: '/dashboard/posts/$id'
      path: '/posts/$id'
      fullPath: '/dashboard/posts/$id'
      preLoaderRoute: typeof DashboardPostsIdRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/posts/$id/': {
      id: '/dashboard/posts/$id/'
      path: '/'
      fullPath: '/dashboard/posts/$id/'
      preLoaderRoute: typeof DashboardPostsIdIndexRouteImport
      parentRoute: typeof DashboardPostsIdRouteRoute
    }
    '/dashboard/posts/$id/edit': {
      id: '/dashboard/posts/$id/edit'
      path: '/edit'
      fullPath: '/dashboard/posts/$id/edit'
      preLoaderRoute: typeof DashboardPostsIdEditRouteImport
      parentRoute: typeof DashboardPostsIdRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(AuthRouteRouteChildren)

interface DashboardPostsIdRouteRouteChildren {
  DashboardPostsIdEditRoute: typeof DashboardPostsIdEditRoute
  DashboardPostsIdIndexRoute: typeof DashboardPostsIdIndexRoute
}

const DashboardPostsIdRouteRouteChildren: DashboardPostsIdRouteRouteChildren = {
  DashboardPostsIdEditRoute: DashboardPostsIdEditRoute,
  DashboardPostsIdIndexRoute: DashboardPostsIdIndexRoute,
}

const DashboardPostsIdRouteRouteWithChildren = DashboardPostsIdRouteRoute._addFileChildren(
  DashboardPostsIdRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardPostsIdRouteRoute: typeof DashboardPostsIdRouteRouteWithChildren
  DashboardPostsNewRoute: typeof DashboardPostsNewRoute
  DashboardPostsIndexRoute: typeof DashboardPostsIndexRoute
  DashboardProductsIndexRoute: typeof DashboardProductsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardPostsIdRouteRoute: DashboardPostsIdRouteRouteWithChildren,
  DashboardPostsNewRoute: DashboardPostsNewRoute,
  DashboardPostsIndexRoute: DashboardPostsIndexRoute,
  DashboardProductsIndexRoute: DashboardProductsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
